service: shortlinker
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  memorySize: 256
  timeout: 10
  deploymentBucket:
    name: myfirsttestbucket112

functions:
  registerUser:
    handler: src/auth/register/dist/register.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /register
          method: POST
    environment:
      USERS_TABLE: "users"
  loginUser:
    handler: src/auth/login/dist/login.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /login
          method: POST
    environment:
      USERS_TABLE: "users"
  authorizer:
    handler: src/auth/authorizer/dist/authorizer.authorize
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
  createLink:
    handler: src/links/createLink/dist/createLink.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /create-link
          method: POST
          authorizer:
            name: authorizer
            type: TOKEN
            identitySource: method.request.header.Authorization
    environment:
      TABLE_NAME: "links"
  deactivateLink:
    handler: src/links/deactivateLink/dist/deactivateLink.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /deactivate-link/{linkId}
          method: PUT
          authorizer:
            name: authorizer
            type: TOKEN
            identitySource: method.request.header.Authorization
    environment:
      TABLE_NAME: "links"
  redirect:
    handler: src/links/redirect/dist/redirect.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /redirect/{linkId}
          method: GET
          authorizer:
            name: authorizer
            type: TOKEN
            identitySource: method.request.header.Authorization
    environment:
      TABLE_NAME: "links"
  listLinks:
    handler: src/links/listLinks/dist/listLinks.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    events:
      - http:
          path: /listLinks
          method: GET
          authorizer:
            name: authorizer
            type: TOKEN
            identitySource: method.request.header.Authorization
    environment:
      TABLE_NAME: "links"
  sendNotificationToQueue:
    handler: src/notifications/sendNotificationToQueue/dist/sendNotificationToQueue.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    environment:
      TABLE_NAME: "links"
      QUEUE_URL: "https://sqs.eu-central-1.amazonaws.com/YOUR_ACCOUNT_ID/sendMessageQueue"
    events:
      - eventBridge:
          schedule: cron(0 9 * * ? *)

  sendNotificationToUser:
    handler: src/notifications/sendNotificationToUser/dist/sendNotificationToUser.handler
    role: arn:aws:iam::YOUR_ACCOUNT_ID:role/user_register
    environment:
      TABLE_NAME: "users"
    events:
      - sqs: arn:aws:sqs:eu-central-1:YOUR_ACCOUNT_ID:sendMessageQueue
